GET localhost:8080/student

###

POST localhost:8080/student
Content-Type: application/json

{
  "name": "c",
  "address": "c"
}

###

GET localhost:8080/student/1

###

PUT localhost:8080/student/1
Content-Type: application/json

{
  "name": "a_change",
  "address": "b_change"
}

###

DELETE localhost:8080/student/1
